# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [3]:
display(baby_names.head(10))

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [4]:
baby_names = baby_names.drop(columns=['Unnamed: 0', 'Id'])
display(baby_names.head())

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### Step 6. Is there more male or female names in the dataset?

In [5]:
gender_counts = baby_names.groupby('Gender')['Count'].sum()
display(gender_counts)

Gender
F    16380293
M    19041199
Name: Count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [6]:
names = baby_names.groupby('Name')['Count'].sum()
display(names.head())

Name
Aaban        12
Aadan        23
Aadarsh       5
Aaden      3426
Aadhav        6
Name: Count, dtype: int64

### Step 8. How many different names exist in the dataset?

In [7]:
num_different_names = len(names)
display(f"Có {num_different_names} tên khác nhau trong tập dữ liệu.")

'Có 17632 tên khác nhau trong tập dữ liệu.'

### Step 9. What is the name with most occurrences?

In [8]:
name_most_occurrences = names.idxmax()
count_most_occurrences = names.max()
display(f"Tên có số lần xuất hiện nhiều nhất là '{name_most_occurrences}' với {count_most_occurrences} lần.")

"Tên có số lần xuất hiện nhiều nhất là 'Jacob' với 242874 lần."

### Step 10. How many different names have the least occurrences?

In [9]:
min_occurrences = names.min()
num_names_least_occurrences = (names == min_occurrences).sum()
display(f"Có {num_names_least_occurrences} tên khác nhau có số lần xuất hiện ít nhất ({min_occurrences} lần).")

'Có 2578 tên khác nhau có số lần xuất hiện ít nhất (5 lần).'

### Step 11. What is the median name occurrence?

In [10]:
median_occurrence = names.median()
display(f"Giá trị trung vị của các lần xuất hiện tên là: {median_occurrence}")

'Giá trị trung vị của các lần xuất hiện tên là: 49.0'

### Step 12. What is the standard deviation of names?

In [11]:
std_deviation_names = names.std()
display(f"Độ lệch chuẩn của các tên là: {std_deviation_names}")

'Độ lệch chuẩn của các tên là: 11006.069467891111'

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [12]:
name_occurrences_summary = names.describe()
display(name_occurrences_summary)

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64